version: '3.8'
services:
  database:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - crm-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  grafana:
    image: grafana/grafana:12.0.2
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
    volumes:
     -  ./devops/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      - loki
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - crm-network

  prometheus:
    image: prom/prometheus:v3.4.2
    ports:
      - "9090:9090"
    volumes:
      - ./devops/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - crm-network

  loki:
    image: grafana/loki:latest
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    networks:
      - crm-network
    depends_on:
      - promtail

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - ./logs:/etc/host-logs:ro   
      - ./devops/promtail/promtail.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - crm-network

volumes:
  db_data:
  prometheus_data:


networks:
  crm-network:
    driver: bridge
