logging:
  file:
    name: logs/crm-web.log
  level:
    root: info
server:
  port: 8080
spring:
  jpa:
    generate-ddl: false
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      "[hibernate.generate_statistics]": true
  output:
    ansi:
      enabled: always
  flyway:
    driver-class-name: com.mysql.cj.jdbc.Driver
    baseline-on-migrate: true
    baseline-version: "0"
    enabled:  true
  config:
    import:
      - optional:file:.env[.properties]
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}  

# https://docs.spring.io/spring-boot/reference/actuator/endpoints.html
management:
  endpoints:
    web:
      exposure:
        include:
        - metrics
        - loggers
        - health
        - http
        - info
        - prometheus
        - auditevents
        # - logfile
  endpoint:
    health:
      access: read-only
      show-details: always
    metrics:
      access: read-only
    auditevents:
      access: read-only
    prometheus:
      access: read-only