spring:
  config:
    import:
    - optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name:  org.h2.Driver
    username: sa
    password:
  sql:
    init:
      platform: org.hibernate.dialect.H2Dialect